title: AI Blog
# Your name to show in the footer
author: Mike Huisman
email: m.huisman.8@umail.leidenuniv.nl
description: >- # this means to ignore newlines until "baseurl:"
  Artificial Intelligence made understandable.   
baseurl: "/aiblog/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social-network-links:
  email: "m.huisman.8@umail.leidenuniv.nl"
  github: mikehuisman
  twitter: MikeHuisman8
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  
#github:
#  is_project_page: false
  
# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
